database_url: postgres://postgres:12adib%40was@127.0.0.1/nota_db?sslmode=disable
server_port: :5600
bootstrap:
  initial:
    admin_email: admin@example.com
    admin_username: admin
    admin_displayname: "Admin"
    admin_password: password123
    org_name: "Admin"
    org_description: "Admin Organization"
user_jwt:
  signing_key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFkbWluIiwiZW1haWwiOiJhZG1pbkBleGFtcGxlLmNvbSIsInVzZXJfaWQiOjEsIm9yZ19pZCI6MSwib3JnX25hbWUiOiJBZG1pbiIsImV4cCI6MTczMzM1NzQzMn0.eo3D2M46sh-92ccPLCUM-9LFm6UAQ44_OpdHzg89IH8
  duration: 720h
smtp:
  email: osborne.sauer@ethereal.email
  username: osborne.sauer@ethereal.email
  password: BfpAahSQnNTfRfug5b
  host: smtp.ethereal.email
  port: 587
