// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AppUser struct {
	UserID         int32              `db:"user_id" json:"user_id"`
	OrganizationID int32              `db:"organization_id" json:"organization_id"`
	Username       string             `db:"username" json:"username"`
	DisplayName    string             `db:"display_name" json:"display_name"`
	Email          string             `db:"email" json:"email"`
	Password       string             `db:"password" json:"password"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	IsActive       pgtype.Bool        `db:"is_active" json:"is_active"`
	IsLocked       pgtype.Bool        `db:"is_locked" json:"is_locked"`
}

type LoginHistory struct {
	LoginID     pgtype.Int4        `db:"login_id" json:"login_id"`
	UserID      pgtype.Int4        `db:"user_id" json:"user_id"`
	Username    pgtype.Text        `db:"username" json:"username"`
	LoginTime   pgtype.Timestamptz `db:"login_time" json:"login_time"`
	LoginStatus pgtype.Bool        `db:"login_status" json:"login_status"`
}

type Organization struct {
	OrganizationID          int32              `db:"organization_id" json:"organization_id"`
	OrganizationName        string             `db:"organization_name" json:"organization_name"`
	OrganizationDescription string             `db:"organization_description" json:"organization_description"`
	CreatedAt               pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
